services:
  - type: web
    name: financecompare
    env: python
    region: oregon
    plan: free
    startCommand: "cd api && gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false