services:
  - type: web
    name: financecompare
    env: python
    region: oregon
    plan: free
    rootDir: api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false